language: node_js
node_js:
- node
dist: xenial
addons:
  chrome: stable
env:
- CHROME_BIN=google-chrome-stable
notifications:
  slack:
    secure: a3Z5A1nzPLsJ6m8wuulIiw/69Uf8cQRCTYgii5Zfup/Z0fu5+x8e62AzaKhvi57V4VVFK5VUnGqMe8iC/E5slsYYI7QbsCvDfcxqIAruGq/sGsp44z3sc62N65Pr0allR2yspzLlgbgJ8oUsKEm5lK2Po5V79rQb4zuitU63wMY=
